import type {Investigation} from '../src/types.js';
const base='2026-08-18T14:';
export const demo:Investigation={
incident:{id:'inc-1042',number:1042,title:'Checkout API failure',description:'Elevated 500 responses on checkout after the v2.8.1 production deployment. Customers could browse but could not complete purchases.',severity:'high',status:'investigating',service:'checkout-api',environment:'production',startTime:base+'32:00.000Z',confidence:.91,affectedComponents:['checkout-api','postgres-primary','payment-adapter'],rootCause:'Database connection pool exhaustion caused by additional sequential queries in v2.8.1',createdAt:base+'36:00.000Z'},
evidence:[
{id:'ev-log',name:'checkout-application.log',type:'log',size:'2.4 MB',status:'ready',confidence:.96,coverage:'14:20–14:48 UTC',entities:['checkout-api','PoolTimeout','HTTP 500'],excerpt:'14:32:11 ERROR PoolTimeout: unable to acquire connection after 2000ms request_id=req_8f2',reliability:.95},
{id:'ev-metric',name:'production-metrics.csv',type:'metric',size:'84 KB',status:'ready',confidence:.99,coverage:'14:00–15:00 UTC',entities:['db.pool.utilization','p95 latency','5xx rate'],excerpt:'Pool utilization changed from 61% to 98%; z-score 4.82. Error rate lag: +1 minute, r=0.94.',reliability:.99},
{id:'ev-deploy',name:'deployment-v2.8.1.json',type:'deployment',size:'4 KB',status:'ready',confidence:1,coverage:'14:28 UTC',entities:['v2.8.1','commit 8f21c4d','checkout-api'],excerpt:'Production rollout completed at 14:28:43 UTC. Previous version: v2.8.0.',reliability:1},
{id:'ev-git',name:'commit-8f21c4d.diff',type:'git',size:'18 KB',status:'ready',confidence:.94,coverage:'Aug 18, 11:42 UTC',entities:['OrderRepository.ts','getRecommendations','3 queries'],excerpt:'+ await db.query(orderItems)\n+ await db.query(inventory)\n+ await db.query(recommendations)',reliability:.92},
{id:'ev-chat',name:'incident-channel.json',type:'chat',size:'32 KB',status:'ready',confidence:.82,coverage:'14:31–14:53 UTC',entities:['payments','database','rollback'],excerpt:'14:35 Priya: Payment provider dashboard is green. DB pool looks pinned on checkout pods.',reliability:.75},
{id:'ev-arch',name:'checkout-architecture.png',type:'architecture',size:'684 KB',status:'ready',confidence:.88,coverage:'Updated Jul 2026',entities:['API Gateway','Checkout','PostgreSQL','Payment'],excerpt:'Extracted relationship: API Gateway → Checkout API → PostgreSQL; Checkout API → Payment Provider.',reliability:.8},
{id:'ev-report',name:'provider-status-snapshot.png',type:'image',size:'1.1 MB',status:'ready',confidence:.78,coverage:'14:25–14:45 UTC',entities:['Payment provider','p95 latency','status green'],excerpt:'Status indicators are green; latency remains inside historical band.',reliability:.7}],
timeline:[
{id:'t1',time:base+'25:00.000Z',title:'Database operating normally',detail:'Pool utilization 58–63%; p95 query latency 42 ms.',kind:'metric',evidenceIds:['ev-metric'],confidence:.99},
{id:'t2',time:base+'28:43.000Z',title:'Deployment v2.8.1 completed',detail:'Commit 8f21c4d rolled out to all checkout-api pods.',kind:'deployment',evidenceIds:['ev-deploy','ev-git'],confidence:1},
{id:'t3',time:base+'29:20.000Z',title:'Query volume begins rising',detail:'Queries per checkout increased from 4.1 to 7.0.',kind:'anomaly',evidenceIds:['ev-metric','ev-git'],confidence:.95},
{id:'t4',time:base+'31:04.000Z',title:'Database latency increases',detail:'p95 latency crosses 400 ms; pool utilization reaches 91%.',kind:'anomaly',evidenceIds:['ev-metric'],confidence:.98},
{id:'t5',time:base+'32:11.000Z',title:'Checkout 500 errors spike',detail:'PoolTimeout errors appear across all checkout pods.',kind:'error',evidenceIds:['ev-log','ev-metric'],confidence:.99},
{id:'t6',time:base+'33:00.000Z',title:'Connection pool saturated',detail:'Utilization reaches 98%, with 46 waiting requests.',kind:'critical',evidenceIds:['ev-metric','ev-log'],confidence:.99},
{id:'t7',time:base+'36:00.000Z',title:'Incident alert triggered',detail:'Checkout success-rate SLO alert fired.',kind:'alert',evidenceIds:['ev-log'],confidence:.96},
{id:'t8',time:base+'46:18.000Z',title:'Rollback completed',detail:'v2.8.0 restored; pool and error rate recover within 90 seconds.',kind:'recovery',evidenceIds:['ev-deploy','ev-metric'],confidence:.98}],
hypotheses:[
{id:'h1',rank:1,title:'Database connection pool exhaustion',summary:'Three new sequential queries in v2.8.1 increased connection hold time, saturated the checkout pool, and caused request timeouts.',confidence:.91,status:'leading',supporting:['Deployment preceded anomaly by 37 seconds','Pool utilization reached 98%','New code added three DB queries','Rollback reversed both saturation and errors'],contradicting:['Database infrastructure itself reported no outage'],missing:['Load-test reproduction under production concurrency'],score:{direct:30,temporal:18,independent:15,verification:20,plausibility:15,contradiction:-7,total:91}},
{id:'h2',rank:2,title:'Payment provider degradation',summary:'An upstream provider slowdown could have held checkout connections open and caused cascading failures.',confidence:.28,status:'alternative',supporting:['Some payment requests exceeded 800 ms'],contradicting:['Provider status and regional probes remained green','Pool saturation began before payment latency','Rollback fixed symptoms without provider change'],missing:['Provider request-level trace sample'],score:{direct:8,temporal:5,independent:5,verification:4,plausibility:12,contradiction:-6,total:28}},
{id:'h3',rank:3,title:'Transient network instability',summary:'Network packet loss between checkout and PostgreSQL may explain query latency and timeouts.',confidence:.11,status:'alternative',supporting:['Two isolated TCP retransmit warnings'],contradicting:['No cross-service network errors','Error onset aligns with deploy','Rollback resolved incident'],missing:['Pod-level packet capture'],score:{direct:3,temporal:2,independent:2,verification:1,plausibility:8,contradiction:-5,total:11}}],
recommendations:[
{id:'r1',category:'Immediate mitigation',title:'Keep v2.8.1 rolled back',detail:'Hold rollout until query fan-out is removed and load-tested.',evidenceIds:['ev-deploy','ev-metric'],done:true},
{id:'r2',category:'Short-term fix',title:'Batch recommendation queries',detail:'Replace three sequential queries with one bounded query and add request-scoped caching.',evidenceIds:['ev-git'],done:false},
{id:'r3',category:'Long-term prevention',title:'Add database budget to CI',detail:'Fail performance tests when queries per checkout or pool wait time exceed the baseline.',evidenceIds:['ev-git','ev-metric'],done:false},
{id:'r4',category:'Observability',title:'Alert on pool waiters by endpoint',detail:'Track utilization, wait queue, and acquisition latency split by route and release.',evidenceIds:['ev-metric'],done:false}],
trace:[
{id:'x1',at:'00:01',type:'plan',title:'Investigation started',summary:'Prioritized the deployment window, error signatures, and saturation metrics.',status:'complete'},
{id:'x2',at:'00:03',type:'tool',title:'Deployment history retrieved',summary:'Checked releases because the failure began abruptly.',tool:'inspect_deployments',durationMs:184,status:'complete'},
{id:'x3',at:'00:05',type:'finding',title:'Suspicious commit found',summary:'The deployed commit adds three queries to the checkout request path.',tool:'inspect_git_diff',durationMs:326,status:'complete'},
{id:'x4',at:'00:08',type:'tool',title:'Metrics analyzed',summary:'Change-point and lag analysis found pool saturation immediately before 500 errors.',tool:'query_metrics',durationMs:412,status:'complete'},
{id:'x5',at:'00:11',type:'verification',title:'Alternative tested',summary:'Provider degradation was tested against independent status and trace evidence.',tool:'compare_hypotheses',durationMs:264,status:'complete'},
{id:'x6',at:'00:14',type:'verification',title:'Rollback verified cause',summary:'Pool pressure and errors recovered together after rollback.',tool:'find_related_events',durationMs:198,status:'complete'},
{id:'x7',at:'00:16',type:'finding',title:'Investigation completed',summary:'Evidence threshold reached with four independent sources and one contradiction.',status:'complete'}],
graph:{nodes:[
{id:'n1',label:'v2.8.1',type:'deployment',x:70,y:130},{id:'n2',label:'Commit 8f21c',type:'commit',x:220,y:70},{id:'n3',label:'+3 DB queries',type:'change',x:380,y:130},{id:'n4',label:'Pool 98%',type:'metric',x:540,y:70},{id:'n5',label:'Checkout 500s',type:'error',x:690,y:130},{id:'n6',label:'Pool exhaustion',type:'rootcause',x:540,y:230,confidence:.91},{id:'n7',label:'Provider healthy',type:'evidence',x:300,y:260}],edges:[
{id:'g1',source:'n1',target:'n2',label:'deployed-with',strength:1},{id:'g2',source:'n2',target:'n3',label:'modified-by',strength:.95},{id:'g3',source:'n3',target:'n4',label:'caused-by',strength:.88},{id:'g4',source:'n4',target:'n5',label:'occurred-before',strength:.94},{id:'g5',source:'n4',target:'n6',label:'supports',strength:.96},{id:'g6',source:'n7',target:'n6',label:'supports',strength:.6}]},
metrics:Array.from({length:13},(_,i)=>({time:`14:${String(24+i*2).padStart(2,'0')}`,latency:i<3?42+i*3:i<11?60+(i-2)*75:65,errors:i<4?.2:i<11?2+(i-3)*3.2:.7,pool:i<3?59+i:i<11?65+(i-2)*5.5:62,cpu:42+Math.sin(i)*5}))};
